import {
  EMPLOYMENT_TYPE,
  FILE_TYPE,
  IFormInput,
  INPUT_TYPE,
  INumberFormInput,
  ISelectFormInput,
  ITextFormInput,
  SETTING_CATEGORY,
  SETTING_COLLECTION,
} from "sources-types";
import { JoiSchemaBuilder } from "../utils/validator";
import {
  IMAGE_FILE_SCHEMA,
  PDF_FILE_SCHEMA,
  SETTINGS_SCHEMA_GENERATOR,
  SIGNUP_PHONE_NUMBER,
} from "../joiSchema";
import * as Joi from "joi";

export interface IFileFormInput extends IFormInput {
  value: string;
  type: INPUT_TYPE.FILE;
  documentPath: string;
  documentCategory: string;
  schema: Joi.ObjectSchema | Joi.ArraySchema;
}

export type IForm =
  | ITextFormInput
  | IFileFormInput
  | ISelectFormInput
  | INumberFormInput;

export const POST_EDIT_FORM: IForm[] = [
  {
    id: "content",
    type: INPUT_TYPE.TEXTAREA,
    key: "content",
    label: "Content",
    value: "",
    icon: "mail",
    hint: "Register Your Email",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "video",
    type: INPUT_TYPE.TEXT,
    label: "Video Embed URL",
    key: "video",
    value: "",
    icon: "mail",
    hint: "Register Your Email",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "image",
    type: INPUT_TYPE.FILE,
    label: "Your Image",
    key: "image",
    value: "",
    icon: "mail",
    hint: "Register Your Email",
    documentPath: "postImage",
    documentCategory: "blog",
    schema: IMAGE_FILE_SCHEMA({
      type: [FILE_TYPE.JPEG, FILE_TYPE.GIF, FILE_TYPE.PNG],
      name: "image",
      size: 5242880,
    }),
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const EDIT_ARTICLE_FORM: IForm[] = [
  {
    id: "title",
    type: INPUT_TYPE.TEXT,
    label: "Blog Title",
    key: "title",
    value: "",
    icon: "article",
    hint: "Article Title",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "subTitle",
    type: INPUT_TYPE.TEXT,
    label: "Blog SubTitle",
    key: "subTitle",
    value: "",
    icon: "article",
    hint: "Article Sub-Title",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "description",
    type: INPUT_TYPE.TEXTAREA,
    label: "Blog Description",
    key: "description",
    value: "",
    icon: "article",
    hint: "Article Description",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const USER_LOGIN_FORM: IForm[] = [
  {
    id: "email",
    type: INPUT_TYPE.EMAIL,
    label: "Your Email",
    key: "email",
    value: "",
    icon: "mail",
    hint: "Register Your Email",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "password",
    type: INPUT_TYPE.PASSWROD,
    label: "Your Password",
    key: "password",
    value: "",
    icon: "key",
    hint: "Enter Password",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const PHONE_VERIFY: IForm[] = [
  {
    id: "verifyCode",
    type: INPUT_TYPE.NUMBER,
    label: "Verify Code",
    key: "verifyCode",
    value: 0,
    hint: "Edit Name",
    icon: "phone",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const USER_SIGNUP_FORM: IForm[] = [
  {
    id: "displayName",
    type: INPUT_TYPE.TEXT,
    label: "Your Display Name",
    key: "displayName",
    value: "",
    hint: "Edit Name",
    icon: "accessibility_new",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.EMAIL,
    label: "Your Email",
    key: "email",
    value: "",
    hint: "Edit Email",
    icon: "mail",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "area",
    type: INPUT_TYPE.SELECT,
    label: "Select Area",
    key: "area",
    value: [] as any,
    hint: "Area",
    icon: "dialpad",
    selection: ["+1"],
    column: {
      xs: 2,
      sm: 2,
      md: 2,
      lg: 2,
      xl: 2,
    },
  },
  {
    id: "phone",
    type: INPUT_TYPE.TEXT,
    label: "Your phone",
    key: "phone",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 10,
      sm: 10,
      md: 10,
      lg: 10,
      xl: 10,
    },
  },
  {
    id: "password",
    type: INPUT_TYPE.PASSWROD,
    label: "Your Password",
    key: "password",
    value: "",
    hint: "Enter Password",
    icon: "key",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "repeatPassword",
    type: INPUT_TYPE.PASSWROD,
    label: "Repeat your Password",
    key: "repeatPassword",
    value: "",
    hint: "Enter Password",
    icon: "key",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const ACCOUNT_INFO: IForm[] = [
  {
    id: "displayName",
    type: INPUT_TYPE.TEXT,
    label: "Display Name",
    key: "displayName",
    value: "",
    hint: "Account Name",
    icon: "badge",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "userId",
    type: INPUT_TYPE.TEXT,
    label: "User Id",
    key: "userId",
    value: "",
    hint: "User Id",
    icon: "badge",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.TEXT,
    label: "Email",
    key: "email",
    value: "",
    hint: "Email",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "emailVerified",
    type: INPUT_TYPE.TEXT,
    label: "Email Verified",
    key: "emailVerified",
    value: "",
    hint: "Email",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "isAnonymous",
    type: INPUT_TYPE.TEXT,
    label: "Registed",
    key: "isAnonymous",
    value: "",
    hint: "Email",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "phoneNumber",
    type: INPUT_TYPE.NUMBER,
    label: "Phone Number",
    key: "phoneNumber",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "role",
    type: INPUT_TYPE.TEXT,
    label: "Role",
    key: "role",
    value: "",
    hint: "Email",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const BIOGRAPHY_FORM: IForm[] = [
  {
    id: "biography",
    type: INPUT_TYPE.TEXTAREA,
    label: "Biography",
    key: "biography",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const CASH_ACCOUNTS_RECEIVABLE_FORM: IForm[] = [
  {
    id: "assetType",
    type: INPUT_TYPE.SELECT,
    label: "Asset Type",
    key: "assetType",
    value: [],
    hint: "Email",
    icon: "mail",
    selection: ["Cash", "Account Receivable", "Other Liquid Asset"],
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "financialInstitution",
    type: INPUT_TYPE.SELECT,
    label: "Financial Institution",
    key: "financialInstitution",
    value: [],
    hint: "Email",
    icon: "mail",
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "currentBalance",
    type: INPUT_TYPE.NUMBER,
    label: "Current Balance",
    key: "currentBalance",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lastStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Statement",
    key: "lastStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "noticeOfAssessment",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Notice Of Assessment",
      size: 5242880,
    }),
  },
];

export const TAX_RETURN_FORM: IForm[] = Array(3)
  .fill(0)
  .map((item, index): IForm => {
    const currentYear = new Date().getFullYear();

    return {
      id: "taxReturn_" + (currentYear - index),
      type: INPUT_TYPE.FILE,
      label: "Tax Return " + (currentYear - index),
      key: "taxReturn_" + (currentYear - index),
      value: "",
      hint: "Email",
      icon: "mail",
      column: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 12,
        xl: 12,
      },
      documentPath: "net_worth",
      documentCategory: "tax_return",
      schema: PDF_FILE_SCHEMA({
        type: [FILE_TYPE.PDF],
        name: "Notice Of Assessment",
        size: 5242880,
      }),
    };
  });

export const HOME_ADDRESS_FORM: IForm[] = [
  {
    id: "addressLine1",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 1",
    key: "addressLine1",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "addressLine2",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 2",
    key: "addressLine2",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "Current Balance",
    key: "currentBalance",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "postalCode",
    type: INPUT_TYPE.TEXT,
    label: "Postal Code",
    key: "postalCode",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.SELECT,
    label: "Province",
    key: "province",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Ontario"],
  },
  {
    id: "country",
    type: INPUT_TYPE.SELECT,
    label: "Country",
    key: "country",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Canada"],
  },
];

export const MARKABLE_SECURITY_FORM: IForm[] = [
  {
    id: "financialInstitution",
    type: INPUT_TYPE.SELECT,
    label: "Financial Institution",
    key: "financialInstitution",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "inNameOf",
    type: INPUT_TYPE.TEXT,
    label: "In Name Of",
    key: "inNameOf",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "pledgeAsCollateral",
    type: INPUT_TYPE.TEXT,
    label: "Pledge As Collateral",
    key: "pledgeAsCollateral",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "highestAssetAllocation",
    type: INPUT_TYPE.SELECT,
    label: "Highest Asset Allocation",
    key: "highestAssetAllocation",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.TEXT,
    label: "Market Value",
    key: "marketValue",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.NUMBER,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.NUMBER,
    label: "Month Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lastSecurityStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Security Statement",
    key: "lastSecurityStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Security Statement",
      size: 5242880,
    }),
  },
  {
    id: "lastLoanStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Loan Statement",
    key: "lastLoanStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Loan Statement",
      size: 5242880,
    }),
  },
];

export const TAX_SHELTERED_INVESTMENT_FORM: IForm[] = [
  {
    id: "financialInstitution",
    type: INPUT_TYPE.SELECT,
    label: "Financial Institution",
    key: "financialInstitution",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "inNameOf",
    type: INPUT_TYPE.TEXT,
    label: "In Name Of",
    key: "inNameOf",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "pledgeAsCollateral",
    type: INPUT_TYPE.TEXT,
    label: "Pledge As Collateral",
    key: "pledgeAsCollateral",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "description",
    type: INPUT_TYPE.SELECT,
    label: "Description",
    key: "description",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["RRSP", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.TEXT,
    label: "Market Value",
    key: "marketValue",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "monthlyIncome",
    type: INPUT_TYPE.NUMBER,
    label: "Monthly Income",
    key: "monthlyIncome",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.NUMBER,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.NUMBER,
    label: "Month Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lastSecurityStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Security Statement",
    key: "lastSecurityStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Security Statement",
      size: 5242880,
    }),
  },
  {
    id: "lastLoanStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Loan Statement",
    key: "lastLoanStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Loan Statement",
      size: 5242880,
    }),
  },
];

export const INSURANCE_FORM: IForm[] = [
  {
    id: "insuranceCompany",
    type: INPUT_TYPE.TEXT,
    label: "Insurance",
    key: "insuranceCompany",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "beneficiary",
    type: INPUT_TYPE.TEXT,
    label: "Beneficiary",
    key: "beneficiary",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "type",
    type: INPUT_TYPE.SELECT,
    label: "Type",
    key: "type",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["RRSP", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "faceValue",
    type: INPUT_TYPE.TEXT,
    label: "faceValue",
    key: "faceValue",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "monthlyPremium",
    type: INPUT_TYPE.TEXT,
    label: "Monthly Premium",
    key: "monthlyPremium",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "cashSurrenderValue",
    type: INPUT_TYPE.TEXT,
    label: "Cash Surrender Value",
    key: "cashSurrenderValue",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "policyLoans",
    type: INPUT_TYPE.TEXT,
    label: "Policy Loans",
    key: "policyLoans",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.NUMBER,
    label: "Month Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lastSecurityStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Security Statement",
    key: "lastSecurityStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Security Statement",
      size: 5242880,
    }),
  },
  {
    id: "lastLoanStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Loan Statement",
    key: "lastLoanStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Loan Statement",
      size: 5242880,
    }),
  },
];

export const REAL_ESTATE_FORM: IForm[] = [
  {
    id: "typeOfResidence",
    type: INPUT_TYPE.SELECT,
    label: "Type Of Residence",
    key: "typeOfResidence",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["RRSP", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "titleInNameOf",
    type: INPUT_TYPE.TEXT,
    label: "Title In Name Of",
    key: "titleInNameOf",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "ownership",
    type: INPUT_TYPE.TEXT,
    label: "Title In Name Of",
    key: "ownership",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "dateAcquired",
    type: INPUT_TYPE.DATE,
    label: "Date Acquired",
    key: "dateAcquired",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "addressLine1",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 1",
    key: "addressLine1",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "Current Balance",
    key: "currentBalance",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "postalCode",
    type: INPUT_TYPE.TEXT,
    label: "Postal Code",
    key: "postalCode",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.SELECT,
    label: "Province",
    key: "province",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Ontario"],
  },
  {
    id: "country",
    type: INPUT_TYPE.SELECT,
    label: "Country",
    key: "country",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Canada"],
  },
  {
    id: "purchasePrice",
    type: INPUT_TYPE.NUMBER,
    label: "Purchase Price",
    key: "purchasePrice",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.TEXT,
    label: "Market Value",
    key: "marketValue",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "grossIncome",
    type: INPUT_TYPE.NUMBER,
    label: "Gross Income",
    key: "grossIncome",
    value: 0,
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "mainCondoFees",
    type: INPUT_TYPE.TEXT,
    label: "Main Condo Fees",
    key: "mainCondoFees",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "monthlyInsurance",
    type: INPUT_TYPE.TEXT,
    label: "Monthly Insurance",
    key: "monthlyInsurance",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "cashSurrenderValue",
    type: INPUT_TYPE.TEXT,
    label: "Cash Surrender Value",
    key: "cashSurrenderValue",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "lastSecurityStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Security Statement",
    key: "lastSecurityStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },

    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Security Statement",
      size: 5242880,
    }),
  },
  {
    id: "lastLoanStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Loan Statement",
    key: "lastLoanStatement",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "Last Loan Statement",
      size: 5242880,
    }),
  },
];

export const NOTICE_OF_ASSESSMENT_FORM: IForm[] = Array(3)
  .fill(0)
  .map((item, index): IForm => {
    const currentYear = new Date().getFullYear();

    return {
      id: "noticeOfAssessment_" + (currentYear - index),
      type: INPUT_TYPE.FILE,
      label: "Notice Of Assessment " + (currentYear - index),
      key: "noticeOfAssessment_" + (currentYear - index),
      value: "",
      hint: "Email",
      icon: "mail",
      column: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 12,
        xl: 12,
      },
      documentPath: "net_worth",
      documentCategory: "noticeOfAssessment",
      schema: PDF_FILE_SCHEMA({
        type: [FILE_TYPE.PDF],
        name: "Notice Of Assessment",
        size: 5242880,
      }),
    };
  });

export interface ISettingCategory {
  title: string;
  description: string;
  category: string;
  list: IForm[];
  noEdit?: boolean;
  schema: JoiSchemaBuilder;
}

export interface ISettingCategoryTab {
  title: string;
  categories: ISettingCategory[];
}

export const SETTING_COLLECTIONS: Record<
  SETTING_COLLECTION,
  ISettingCategory[]
> = {
  [SETTING_COLLECTION.SECURITY]: [
    {
      title: "Account",
      description: "User Basic Information",
      category: SETTING_CATEGORY.ACCOUNT,
      list: ACCOUNT_INFO,
      noEdit: true,
      schema: SETTINGS_SCHEMA_GENERATOR(
        ACCOUNT_INFO.filter((data) =>
          ["displayName", "phoneNumber"].includes(data.id)
        )
      ),
    },
    {
      title: "Authentication",
      description: "Change Password",
      category: "authentication",
      list: ACCOUNT_INFO,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Recognition",
      description: "Change facial and voice recognition",
      category: "recognition",
      list: ACCOUNT_INFO,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
  ],
  [SETTING_COLLECTION.PERSONAL_PROFILE]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      noEdit: true,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.PERSONAL_RESUME]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      noEdit: true,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.BUSINESS_PROFILE]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      noEdit: true,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.PROFESSIONAL_PROFILE]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.PERSONAL_NET_WORTH]: [
    {
      title: "Tax Return",
      description: "Personal tax return for the last three years",
      category: SETTING_CATEGORY.TAX_RETURN,
      list: TAX_RETURN_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(TAX_RETURN_FORM),
    },
    {
      title: "Notice Of Assessment",
      description: "Personal Notice Of Assessment for the last three years",
      category: SETTING_CATEGORY.NOTICE_OF_ASSESSMENT,
      list: NOTICE_OF_ASSESSMENT_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(NOTICE_OF_ASSESSMENT_FORM),
    },
    {
      title: "Cash And Accounts Receivable",
      description: "asset type, financial institution, statement.",
      category: SETTING_CATEGORY.CASH_ACCOUNTS_RECEIVABLE,
      list: CASH_ACCOUNTS_RECEIVABLE_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(CASH_ACCOUNTS_RECEIVABLE_FORM),
    },
    {
      title: "Markable Securities",
      description: "Change facial and voice recognition",
      category: SETTING_CATEGORY.MARKABLE_SECURITY,
      list: MARKABLE_SECURITY_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(MARKABLE_SECURITY_FORM),
    },
    {
      title: "Tax Sheltered Investment",
      description: "Tax sheltered investment",
      category: SETTING_CATEGORY.TAX_SHELTERED_INVESTMENT,
      list: TAX_SHELTERED_INVESTMENT_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(TAX_SHELTERED_INVESTMENT_FORM),
    },
    {
      title: "Insurance",
      description: "Insurance",
      category: SETTING_CATEGORY.INSURANCE,
      list: INSURANCE_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(INSURANCE_FORM),
    },
    {
      title: "Real Estate",
      description: "Real Estate Property",
      category: SETTING_CATEGORY.REAL_ESTATE,
      list: REAL_ESTATE_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(REAL_ESTATE_FORM),
    },
    {
      title: "Vehicles",
      description: "Personal Vehicles",
      category: SETTING_CATEGORY.VEHICLES,
      list: REAL_ESTATE_FORM,
      schema: SETTINGS_SCHEMA_GENERATOR(REAL_ESTATE_FORM),
    },
  ],
};

export const EMPLOYMENT: IForm[] = [
  {
    id: "title",
    type: INPUT_TYPE.TEXT,
    label: "Most Recent Job Title",
    key: "title",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "institution",
    type: INPUT_TYPE.TEXT,
    label: "Most Recent Company",
    key: "institution",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "degree",
    type: INPUT_TYPE.TEXT,
    label: "Degree",
    key: "degree",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "year",
    type: INPUT_TYPE.TEXT,
    label: "Year",
    key: "year",
    value: "",
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "employment_type",
    type: INPUT_TYPE.SELECT,
    label: "Employment type",
    key: "employment_type",
    value: [],
    hint: "Email",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: [EMPLOYMENT_TYPE.PERMANENT_FULL_TIME],
  },
];
