import {
  EMPLOYMENT_TYPE,
  FILE_TYPE,
  IFormInput,
  IMoneyFormInput,
  INPUT_TYPE,
  INumberFormInput,
  ISelectFormInput,
  ITextFormInput,
  IToggleFormInput,
  PartialRecord,
  SETTING_CATEGORY,
  SETTING_COLLECTION,
} from "type-sources";
import { JoiSchemaBuilder } from "../utils/validator";
import {
  IMAGE_FILE_SCHEMA,
  PDF_FILE_SCHEMA,
  SETTINGS_SCHEMA_GENERATOR,
} from "../joiSchema";
import * as Joi from "joi";

export interface IFileFormInput extends IFormInput {
  value: string[];
  type: INPUT_TYPE.FILE;
  documentPath: string;
  documentCategory: string;
  schema: Joi.ObjectSchema | Joi.ArraySchema;
}

export type IForm =
  | IToggleFormInput
  | ITextFormInput
  | IFileFormInput
  | ISelectFormInput
  | INumberFormInput
  | IMoneyFormInput;

export const POST_EDIT_FORM: IForm[] = [
  {
    id: "content",
    type: INPUT_TYPE.TEXTAREA,
    key: "content",
    label: "Content",
    value: "",
    icon: "mail",
    hint: "Register Your Email",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "image",
    type: INPUT_TYPE.FILE,
    label: "Your Image",
    key: "image",
    value: [],
    icon: "mail",
    hint: "Register Your Email",
    documentPath: "postImage",
    documentCategory: "blog",
    schema: IMAGE_FILE_SCHEMA({
      type: [FILE_TYPE.JPEG, FILE_TYPE.GIF, FILE_TYPE.PNG],
      name: "image",
      size: 5242880,
    }),
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const EDIT_ARTICLE_FORM: IForm[] = [
  {
    id: "title",
    type: INPUT_TYPE.TEXT,
    label: "Blog Title",
    key: "title",
    value: "",
    icon: "article",
    hint: "Article Title",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "subTitle",
    type: INPUT_TYPE.TEXT,
    label: "Blog SubTitle",
    key: "subTitle",
    value: "",
    icon: "article",
    hint: "Article Sub-Title",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "description",
    type: INPUT_TYPE.TEXTAREA,
    label: "Blog Description",
    key: "description",
    value: "",
    icon: "article",
    hint: "Article Description",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const USER_LOGIN_FORM: IForm[] = [
  {
    id: "email",
    type: INPUT_TYPE.EMAIL,
    label: "Your Email",
    key: "email",
    value: "",
    icon: "mail",
    hint: "Register Your Email",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "password",
    type: INPUT_TYPE.PASSWROD,
    label: "Your Password",
    key: "password",
    value: "",
    icon: "key",
    hint: "Enter Password",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const PHONE_REGISTER: IForm[] = [
  {
    id: "area",
    type: INPUT_TYPE.SELECT,
    label: "Select Area",
    key: "area",
    value: [] as any,
    hint: "Area",
    icon: "dialpad",
    selection: ["+1"],
    column: {
      xs: 12,
      sm: 12,
      md: 2,
      lg: 2,
      xl: 2,
    },
  },
  {
    id: "phone",
    type: INPUT_TYPE.PHONE,
    label: "Your phone",
    key: "phone",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 12,
      sm: 12,
      md: 10,
      lg: 10,
      xl: 10,
    },
  },
];

export const PHONE_VERIFY: IForm[] = [
  {
    id: "verifyCode",
    type: INPUT_TYPE.TEXT,
    label: "Verify Code",
    key: "verifyCode",
    value: "",
    hint: "Check Your Phone Text To Get Verify Code",
    icon: "phone",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const USER_SIGNUP_FORM: IForm[] = [
  {
    id: "displayName",
    type: INPUT_TYPE.TEXT,
    label: "Your Display Name",
    key: "displayName",
    value: "",
    hint: "Edit Name",
    icon: "accessibility_new",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.EMAIL,
    label: "Your Email",
    key: "email",
    value: "",
    hint: "Edit Email",
    icon: "mail",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "area",
    type: INPUT_TYPE.SELECT,
    label: "Area",
    key: "area",
    value: [] as any,
    hint: "Area",
    icon: "dialpad",
    selection: ["+1"],
    column: {
      xs: 4,
      sm: 4,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "phone",
    type: INPUT_TYPE.PHONE,
    label: "Your phone",
    key: "phone",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 8,
      sm: 8,
      md: 8,
      lg: 8,
      xl: 8,
    },
  },
  {
    id: "password",
    type: INPUT_TYPE.PASSWROD,
    label: "Your Password",
    key: "password",
    value: "",
    hint: "Enter Password",
    icon: "key",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "repeatPassword",
    type: INPUT_TYPE.PASSWROD,
    label: "Repeat your Password",
    key: "repeatPassword",
    value: "",
    hint: "Enter Password",
    icon: "key",
    error: "",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const PERSONAL_INFORMATION_FORM: IForm[] = [
  {
    id: "firstName",
    type: INPUT_TYPE.TEXT,
    label: "First Name",
    key: "firstName",
    value: "",
    hint: "First Name",
    icon: "monetization_on",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "middleName",
    type: INPUT_TYPE.TEXT,
    label: "Middle Name",
    key: "middleName",
    value: "",
    hint: "Middle Name",
    icon: "monetization_on",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastName",
    type: INPUT_TYPE.TEXT,
    label: "Last Name",
    key: "lastName",
    value: "",
    hint: "Last Name",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "equifaxScore",
    type: INPUT_TYPE.TEXT,
    label: "Equifax Score",
    key: "equifaxScore",
    value: "",
    hint: "Equifax Score",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "socialInsuranceNumber",
    type: INPUT_TYPE.TEXT,
    label: "Social Insurance Number",
    key: "socialInsuranceNumber",
    value: "",
    hint: "Social Insurance Number",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "birthday",
    type: INPUT_TYPE.DATE,
    label: "Birthday",
    key: "birthday",
    value: "",
    hint: "dd/mm/yyyy",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.TEXT,
    label: "Email",
    key: "email",
    value: "",
    hint: "Your Email",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "phone",
    type: INPUT_TYPE.PHONE,
    label: "Phone",
    key: "phone",
    value: "",
    hint: "Your Cell Phone",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "maritalStatus",
    type: INPUT_TYPE.SELECT,
    label: "Marital Status",
    key: "maritalStatus",
    value: "",
    hint: "Martial Status",
    icon: "badge",
    selection: ["single", "married", "common law"],
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "dependant",
    type: INPUT_TYPE.TEXT,
    label: "Dependants",
    key: "dependant",
    value: "",
    hint: "Dependants",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "address",
    type: INPUT_TYPE.TEXT,
    label: "Address",
    key: "address",
    value: "",
    hint: "Home Address",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "address2",
    type: INPUT_TYPE.TEXT,
    label: "Address 2",
    key: "address2",
    value: "",
    hint: "Home Address 2",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "City",
    key: "city",
    value: "",
    hint: "City",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.TEXT,
    label: "Province",
    key: "province",
    value: "",
    hint: "province",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "country",
    type: INPUT_TYPE.TEXT,
    label: "Country",
    key: "country",
    value: "",
    hint: "country",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "postal",
    type: INPUT_TYPE.TEXT,
    label: "Postal",
    key: "postal",
    value: "",
    hint: "postal",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "residence",
    type: INPUT_TYPE.SELECT,
    label: "Residence",
    key: "residence",
    value: "",
    hint: "Residence",
    icon: "badge",
    selection: ["Rent", "Own", "Others"],
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "currentAddressInYears",
    type: INPUT_TYPE.NUMBER,
    label: "Current Address In Years",
    key: "currentAddressInYears",
    value: 0,
    hint: "Residence",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "currentAddressInMonths",
    type: INPUT_TYPE.NUMBER,
    label: "Current Address In Years",
    key: "currentAddressInYears",
    value: 0,
    hint: "Residence",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "occupation",
    type: INPUT_TYPE.TEXT,
    label: "occupation",
    key: "occupation",
    value: "",
    hint: "Occupation",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "title",
    type: INPUT_TYPE.TEXT,
    label: "Title",
    key: "title",
    value: "",
    hint: "Job Title",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "responsibilities",
    type: INPUT_TYPE.TEXT,
    label: "Responsibilities",
    key: "responsibilities",
    value: "",
    hint: "Job Responsibilities",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerName",
    type: INPUT_TYPE.TEXT,
    label: "Employer Name",
    key: "employerName",
    value: "",
    hint: "Employer Name",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerPhone",
    type: INPUT_TYPE.TEXT,
    label: "Employer Phone",
    key: "employerPhone",
    value: "",
    hint: "Employer Phone",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerAddress",
    type: INPUT_TYPE.TEXT,
    label: "Employer Address",
    key: "employerAddress",
    value: "",
    hint: "Employer Phone",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerAddress2",
    type: INPUT_TYPE.TEXT,
    label: "Employer Address 2",
    key: "employerAddress2",
    value: "",
    hint: "Employer Phone",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerCity",
    type: INPUT_TYPE.TEXT,
    label: "Employer City",
    key: "employerCity",
    value: "",
    hint: "Employer City",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerProvince",
    type: INPUT_TYPE.TEXT,
    label: "Employer Province",
    key: "employerProvince",
    value: "",
    hint: "Employer Province",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerPostal",
    type: INPUT_TYPE.TEXT,
    label: "Employer Postal/Zip",
    key: "employerPostal",
    value: "",
    hint: "Employer Postal/Zip",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "yearsEmployed",
    type: INPUT_TYPE.TEXT,
    label: "Years Employed",
    key: "yearsEmployed",
    value: "",
    hint: "Years Employed",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthsEmployed",
    type: INPUT_TYPE.TEXT,
    label: "Months Employed",
    key: "monthsEmployed",
    value: "",
    hint: "Months Employed",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "financialInstitutionName",
    type: INPUT_TYPE.TEXT,
    label: "Financial Institution Name",
    key: "financialInstitutionName",
    value: "",
    hint: "Financial Institution Name",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "branchLocation",
    type: INPUT_TYPE.TEXT,
    label: "Branch Location",
    key: "branchLocation",
    value: "",
    hint: "Branch Location",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "bankAccountNumber",
    type: INPUT_TYPE.TEXT,
    label: "Bank Account Number",
    key: "bankAccountNumber",
    value: "",
    hint: "Bank Account Number",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
];

export const DEPENDANT_INFO: IForm[] = [
  {
    id: "dependantName",
    type: INPUT_TYPE.TEXT,
    label: "Dependant Name",
    key: "dependantName",
    value: "",
    hint: "Dependant Name",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "relationship",
    type: INPUT_TYPE.TEXT,
    label: "Relationship",
    key: "relationship",
    value: "",
    hint: "Dependant Name",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "ageYears",
    type: INPUT_TYPE.TEXT,
    label: "Age (Years)",
    key: "ageYears",
    value: "",
    hint: "Dependant Name",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyIncome",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Income",
    key: "monthlyIncome",
    value: 0,
    hint: "Monthly Income",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
];

export const SPOUSE_INFO: IForm[] = [
  {
    id: "firstName",
    type: INPUT_TYPE.TEXT,
    label: "First Name",
    key: "firstName",
    value: "",
    hint: "First Name",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "middleName",
    type: INPUT_TYPE.TEXT,
    label: "Middle Name",
    key: "middleName",
    value: "",
    hint: "Middle Name",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastName",
    type: INPUT_TYPE.TEXT,
    label: "Last Name",
    key: "lastName",
    value: "",
    hint: "Last Name",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "socialInsuranceNumber",
    type: INPUT_TYPE.TEXT,
    label: "Social Insurance Number",
    key: "socialInsuranceNumber",
    value: "",
    hint: "Social Insurance Number",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "birthday",
    type: INPUT_TYPE.DATE,
    label: "Birthday",
    key: "birthday",
    value: "",
    hint: "dd/mm/yyyy",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.TEXT,
    label: "Email",
    key: "email",
    value: "",
    hint: "Your Email",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "phone",
    type: INPUT_TYPE.PHONE,
    label: "Phone",
    key: "phone",
    value: "",
    hint: "Your Cell Phone",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "occupation",
    type: INPUT_TYPE.TEXT,
    label: "occupation",
    key: "occupation",
    value: "",
    hint: "Occupation",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerName",
    type: INPUT_TYPE.TEXT,
    label: "Employer Name",
    key: "employerName",
    value: "",
    hint: "Employer Name",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerPhone",
    type: INPUT_TYPE.TEXT,
    label: "Employer Phone",
    key: "employerPhone",
    value: "",
    hint: "Employer Phone",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerAddress",
    type: INPUT_TYPE.TEXT,
    label: "Employer Address",
    key: "employerAddress",
    value: "",
    hint: "Employer Phone",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerAddress2",
    type: INPUT_TYPE.TEXT,
    label: "Employer Address 2",
    key: "employerAddress2",
    value: "",
    hint: "Employer Phone",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerCity",
    type: INPUT_TYPE.TEXT,
    label: "Employer City",
    key: "employerCity",
    value: "",
    hint: "Employer City",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employerProvince",
    type: INPUT_TYPE.TEXT,
    label: "Employer Province",
    key: "employerProvince",
    value: "",
    hint: "Employer Province",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 2,
      lg: 2,
      xl: 2,
    },
  },
  {
    id: "employerPostal",
    type: INPUT_TYPE.TEXT,
    label: "Employer Postal/Zip",
    key: "employerPostal",
    value: "",
    hint: "Employer Postal/Zip",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "yearsEmployed",
    type: INPUT_TYPE.TEXT,
    label: "Years Employed",
    key: "yearsEmployed",
    value: "",
    hint: "Years Employed",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 2,
      lg: 2,
      xl: 2,
    },
  },
  {
    id: "monthsEmployed",
    type: INPUT_TYPE.TEXT,
    label: "Months Employed",
    key: "monthsEmployed",
    value: "",
    hint: "Months Employed",
    icon: "apartment",
    column: {
      xs: 6,
      sm: 6,
      md: 2,
      lg: 2,
      xl: 2,
    },
  },
];

export const ACCOUNT_INFO: IForm[] = [
  {
    id: "displayName",
    type: INPUT_TYPE.TEXT,
    label: "Display Name",
    key: "displayName",
    value: "",
    hint: "Account Name",
    icon: "badge",
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "userId",
    type: INPUT_TYPE.TEXT,
    label: "User Id",
    key: "userId",
    value: "",
    hint: "User Id",
    icon: "badge",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.TEXT,
    label: "Email",
    key: "email",
    value: "",
    hint: "description",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "emailVerified",
    type: INPUT_TYPE.TEXT,
    label: "Email Verified",
    key: "emailVerified",
    value: "",
    hint: "description",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "isAnonymous",
    type: INPUT_TYPE.TEXT,
    label: "Registed",
    key: "isAnonymous",
    value: "",
    hint: "description",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "phoneNumber",
    type: INPUT_TYPE.NUMBER,
    label: "Phone Number",
    key: "phoneNumber",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
  {
    id: "role",
    type: INPUT_TYPE.TEXT,
    label: "Role",
    key: "role",
    value: "",
    hint: "description",
    icon: "mail",
    disabled: true,
    column: {
      xs: 12,
      sm: 12,
      md: 4,
      lg: 4,
      xl: 4,
    },
  },
];

export const BIOGRAPHY_FORM: IForm[] = [
  {
    id: "biography",
    type: INPUT_TYPE.TEXTAREA,
    label: "Biography",
    key: "biography",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
];

export const CASH_ACCOUNTS_RECEIVABLE_FORM: IForm[] = [
  {
    id: "assetType",
    type: INPUT_TYPE.SELECT,
    label: "Asset Type",
    key: "assetType",
    value: "",
    hint: "Select Cash Asset Type",
    icon: "web_asset",
    selection: ["Cash", "Account Receivable", "Other Liquid Asset"],
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "financialInstitution",
    type: INPUT_TYPE.SELECT,
    label: "Financial Institution",
    key: "financialInstitution",
    value: "",
    hint: "Select Cash Financial Institution",
    icon: "monetization_on",
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "currentBalance",
    type: INPUT_TYPE.MONEY,
    label: "Current Balance",
    key: "currentBalance",
    value: 0,
    hint: "Cash Balance",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Statement",
    key: "lastStatement",
    value: [],
    hint: "Last Statement",
    icon: "folder",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
];

export const PERSONAL_INFORMATION_UPLOADS_FORM: IForm[] = Array(3)
  .fill(0)
  .map((item, index): IForm[] => {
    const currentYear = new Date().getFullYear();

    return [
      {
        id: "taxReturn_" + (currentYear - index),
        type: INPUT_TYPE.FILE,
        label: "Tax Return " + (currentYear - index),
        key: "taxReturn_" + (currentYear - index),
        value: [],
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
          xl: 6,
        },
        documentPath: "net_worth",
        documentCategory: "tax_return",
        schema: PDF_FILE_SCHEMA({
          type: [FILE_TYPE.PDF],
          name: "taxReturn_" + (currentYear - index),
          size: 5242880,
        }),
      },
      {
        id: "noticeOfAssessment_" + (currentYear - index),
        type: INPUT_TYPE.FILE,
        label: "Notice Of Assessment " + (currentYear - index),
        key: "noticeOfAssessment_" + (currentYear - index),
        value: [],
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
          xl: 6,
        },
        documentPath: "net_worth",
        documentCategory: "noticeOfAssessment",
        schema: PDF_FILE_SCHEMA({
          type: [FILE_TYPE.PDF],
          name: "noticeOfAssessment_" + (currentYear - index),
          size: 5242880,
        }),
      },
    ];
  })
  .flat();

export const HOME_ADDRESS_FORM: IForm[] = [
  {
    id: "addressLine1",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 1",
    key: "addressLine1",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "addressLine2",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 2",
    key: "addressLine2",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "Current Balance",
    key: "currentBalance",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "postalCode",
    type: INPUT_TYPE.TEXT,
    label: "Postal Code",
    key: "postalCode",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.SELECT,
    label: "Province",
    key: "province",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Ontario"],
  },
  {
    id: "country",
    type: INPUT_TYPE.SELECT,
    label: "Country",
    key: "country",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Canada"],
  },
];

export const MARKABLE_SECURITY_FORM: IForm[] = [
  {
    id: "financialInstitution",
    type: INPUT_TYPE.SELECT,
    label: "Financial Institution",
    key: "financialInstitution",
    value: "",
    hint: "Select the financial institution",
    icon: "account_balance",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "inNameOf",
    type: INPUT_TYPE.TEXT,
    label: "In Name Of",
    key: "inNameOf",
    value: "",
    hint: "In name of",
    icon: "account_balance",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "pledgeAsCollateral",
    type: INPUT_TYPE.TOGGLE,
    label: "Pledge As Collateral",
    key: "pledgeAsCollateral",
    value: false,
    hint: "Pledge As Collateral",
    icon: "account_balance",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "highestAssetAllocation",
    type: INPUT_TYPE.SELECT,
    label: "Highest Asset Allocation",
    key: "highestAssetAllocation",
    value: "",
    hint: "Highest asset allocation",
    icon: "account_balance",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.MONEY,
    label: "Market Value",
    key: "marketValue",
    value: 0,
    hint: "Input the market value",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "marketIncome",
    type: INPUT_TYPE.MONEY,
    label: "Market Income",
    key: "marketIncome",
    value: 0,
    hint: "Input the market income",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyIncome",
    type: INPUT_TYPE.MONEY,
    label: "Month Income",
    key: "monthlyIncome",
    value: 0,
    hint: "Input the monthly income",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "Select your lender",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "Input your loan balance",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.MONEY,
    label: "Month Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "Input your monthly payment",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastSecurityStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Security Statement",
    key: "lastSecurityStatement",
    value: [],
    hint: "Input your last security statement",
    icon: "description",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastSecurityStatement",
      size: 5242880,
    }),
  },
  {
    id: "lastLoanStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Loan Statement",
    key: "lastLoanStatement",
    value: [],
    hint: "Input your last loan statement",
    icon: "description",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastLoanStatement",
      size: 5242880,
    }),
  },
];

export const TAX_SHELTERED_INVESTMENT_FORM: IForm[] = [
  {
    id: "financialInstitution",
    type: INPUT_TYPE.SELECT,
    label: "Financial Institution",
    key: "financialInstitution",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "inNameOf",
    type: INPUT_TYPE.TEXT,
    label: "In Name Of",
    key: "inNameOf",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "pledgeAsCollateral",
    type: INPUT_TYPE.TOGGLE,
    label: "Pledge As Collateral",
    key: "pledgeAsCollateral",
    value: false,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "description",
    type: INPUT_TYPE.SELECT,
    label: "Description",
    key: "description",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["RRSP", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.MONEY,
    label: "Market Value",
    key: "marketValue",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyIncome",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Income",
    key: "monthlyIncome",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.MONEY,
    label: "Month Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastSecurityStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Security Statement",
    key: "lastSecurityStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastSecurityStatement",
      size: 5242880,
    }),
  },
  {
    id: "lastLoanStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Loan Statement",
    key: "lastLoanStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastLoanStatement",
      size: 5242880,
    }),
  },
];

export const INSURANCE_FORM: IForm[] = [
  {
    id: "insuranceCompany",
    type: INPUT_TYPE.TEXT,
    label: "Insurance",
    key: "insuranceCompany",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "beneficiary",
    type: INPUT_TYPE.TEXT,
    label: "Beneficiary",
    key: "beneficiary",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "type",
    type: INPUT_TYPE.SELECT,
    label: "Type",
    key: "type",
    value: "",
    hint: "Select your insurance type",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: [
      "Team Life Insurance",
      "Whole Life Insurance",
      "Universal Life Insurance",
      "Variable Life Insurance",
      "Variable Universal Life Insurance",
      "Simplified Issue Life Insurance",
      "Guaranteed Issue Life Insurance",
      "Final Expense Life Insurance",
      "Group Life Insurance",
      "Other",
    ],
  },
  {
    id: "faceValue",
    type: INPUT_TYPE.TEXT,
    label: "faceValue",
    key: "faceValue",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyPremium",
    type: INPUT_TYPE.TEXT,
    label: "Monthly Premium",
    key: "monthlyPremium",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "cashSurrenderValue",
    type: INPUT_TYPE.TEXT,
    label: "Cash Surrender Value",
    key: "cashSurrenderValue",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "mortgageBalance",
    type: INPUT_TYPE.MONEY,
    label: "Mortgage Balance",
    key: "mortgageBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "mortgagePayment",
    type: INPUT_TYPE.MONEY,
    label: "Mortgage Payment",
    key: "mortgagePayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "2ndMortgagePayment",
    type: INPUT_TYPE.MONEY,
    label: "Second Mortgage Payment",
    key: "2ndMortgagePayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "2ndMortgageLender",
    type: INPUT_TYPE.TEXT,
    label: "Second Mortgage Lender",
    key: "2ndMortgageLender",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "2ndMortgageBalance",
    type: INPUT_TYPE.MONEY,
    label: "Second Mortgage Balance",
    key: "2ndMortgageBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "2ndMortagePmt",
    type: INPUT_TYPE.MONEY,
    label: "Second Mortgage Pmt",
    key: "2ndMortagePmt",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "propertyAppraisal",
    type: INPUT_TYPE.FILE,
    label: "Property Appraisal",
    key: "propertyAppraisal",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "propertyAppraisal",
      size: 5242880,
    }),
  },
  {
    id: "propertyTax",
    type: INPUT_TYPE.FILE,
    label: "Property Tax",
    key: "propertyTax",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "propertyTax",
      size: 5242880,
    }),
  },
  {
    id: "mortageStatement",
    type: INPUT_TYPE.FILE,
    label: "Mortage Statement",
    key: "mortageStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastSecurityStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastSecurityStatement",
      size: 5242880,
    }),
  },
  {
    id: "2ndMortageSmt",
    type: INPUT_TYPE.FILE,
    label: "2nd Mort. Smt.",
    key: "2ndMortage",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastLoanStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "2ndMortageSmt",
      size: 5242880,
    }),
  },
];

export const REAL_ESTATE_FORM: IForm[] = [
  {
    id: "typeOfResidence",
    type: INPUT_TYPE.SELECT,
    label: "Type Of Residence",
    key: "typeOfResidence",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["RRSP", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "titleInNameOf",
    type: INPUT_TYPE.TEXT,
    label: "Title In Name Of",
    key: "titleInNameOf",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "ownership",
    type: INPUT_TYPE.TEXT,
    label: "Title In Name Of",
    key: "ownership",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "dateAcquired",
    type: INPUT_TYPE.DATE,
    label: "Date Acquired",
    key: "dateAcquired",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "addressLine1",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 1",
    key: "addressLine1",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "addressLine2",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 2",
    key: "addressLine2",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "Current Balance",
    key: "currentBalance",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.SELECT,
    label: "Province",
    key: "province",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["Ontario"],
  },
  {
    id: "purchasePrice",
    type: INPUT_TYPE.MONEY,
    label: "Purchase Price",
    key: "purchasePrice",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.MONEY,
    label: "Market Value",
    key: "marketValue",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "grossIncome",
    type: INPUT_TYPE.MONEY,
    label: "Gross Income",
    key: "grossIncome",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "mainCondoFees",
    type: INPUT_TYPE.MONEY,
    label: "Main Condo Fees",
    key: "mainCondoFees",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyInsurance",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Insurance",
    key: "monthlyInsurance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "propertyTax",
    type: INPUT_TYPE.MONEY,
    label: "Property Tax",
    key: "propertyTax",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "mortageBalance",
    type: INPUT_TYPE.MONEY,
    label: "Mortage Balance",
    key: "mortageBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "mortagePayment",
    type: INPUT_TYPE.MONEY,
    label: "Mortage Payment",
    key: "mortagePayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "2ndMortageBalance",
    type: INPUT_TYPE.MONEY,
    label: "2nd Mortage Balance",
    key: "2ndMortageBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "2ndMortgagePayment",
    type: INPUT_TYPE.MONEY,
    label: "Second Mortgage Payment",
    key: "2ndMortgagePayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "insurance",
    type: INPUT_TYPE.FILE,
    label: "Insurance",
    key: "insurance",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "insurance",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "insurance",
      size: 5242880,
    }),
  },
  {
    id: "propertyAppraisal",
    type: INPUT_TYPE.FILE,
    label: "Property Appraisal",
    key: "propertyAppraisal",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "propertyAppraisal",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "propertyAppraisal",
      size: 5242880,
    }),
  },
  {
    id: "propertyTax",
    type: INPUT_TYPE.FILE,
    label: "Property Tax",
    key: "propertyTax",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "propertyTax",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "propertyTax",
      size: 5242880,
    }),
  },
  {
    id: "mortageStatement",
    type: INPUT_TYPE.FILE,
    label: "Mortage Statement",
    key: "mortageStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "insurance",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "mortageStatement",
      size: 5242880,
    }),
  },
  {
    id: "2ndMortageStatement",
    type: INPUT_TYPE.FILE,
    label: "2nd Mortage Statement",
    key: "2ndMortageStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "insurance",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "mortageStatement",
      size: 5242880,
    }),
  },
];

export const VEHICLE_FORM: IForm[] = [
  {
    id: "year",
    type: INPUT_TYPE.TEXT,
    label: "Year",
    key: "year",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "make",
    type: INPUT_TYPE.TEXT,
    label: "Make",
    key: "make",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "model",
    type: INPUT_TYPE.TEXT,
    label: "Model",
    key: "model",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "milage",
    type: INPUT_TYPE.TEXT,
    label: "Milage",
    key: "milage",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "kelleyBlueBookValue",
    type: INPUT_TYPE.MONEY,
    label: "Kelley Blue Book Value",
    key: "kelleyBlueBookValue",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyInsurance",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Insurance",
    key: "monthlyInsurance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.TEXT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "insuranceContract",
    type: INPUT_TYPE.FILE,
    label: "Insurance Contract",
    key: "insuranceContract",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "propertyTax",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "propertyTax",
      size: 5242880,
    }),
  },
  {
    id: "loanStatement",
    type: INPUT_TYPE.FILE,
    label: "Loan Statement",
    key: "loanStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "propertyTax",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "propertyTax",
      size: 5242880,
    }),
  },
];

export const OTHER_ASSEST_FORM: IForm[] = [
  {
    id: "assetType",
    type: INPUT_TYPE.SELECT,
    label: "Asset Type",
    key: "assetType",
    value: "",
    hint: "description",
    icon: "monetization_on",
    selection: ["Cash", "Account Receivable", "Other Liquid Asset"],
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "description",
    type: INPUT_TYPE.TEXT,
    label: "Description",
    key: "description",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "marketValue",
    type: INPUT_TYPE.MONEY,
    label: "Market Value",
    key: "marketValue",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Statement",
    key: "lastStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
];

export const OTHER_LOANS_FORM: IForm[] = [
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "loanPurpose",
    type: INPUT_TYPE.TEXT,
    label: "Loan Purpose",
    key: "loanPurpose",
    value: "",
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "currentBalance",
    type: INPUT_TYPE.MONEY,
    label: "Current Balance",
    key: "currentBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastMonthStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Month Statement",
    key: "lastMonthStatement",
    value: [],
    hint: "description",
    icon: "monetization_on",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastMonthStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastMonthStatement",
      size: 5242880,
    }),
  },
];

export const LINE_OF_CREDIT_FORM: IForm[] = [
  {
    id: "liabilityType",
    type: INPUT_TYPE.SELECT,
    label: "Liability Type",
    key: "liabilityType",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["Credit Cards", "Line Of Credit"],
  },
  {
    id: "lender",
    type: INPUT_TYPE.TEXT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "creditLimit",
    type: INPUT_TYPE.MONEY,
    label: "Credit Limit",
    key: "creditLimit",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "currentBalance",
    type: INPUT_TYPE.MONEY,
    label: "Current Balance",
    key: "currentBalance",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "loanStatement",
    type: INPUT_TYPE.FILE,
    label: "Loan Statement",
    key: "loanStatement",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastMonthStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastMonthStatement",
      size: 5242880,
    }),
  },
];

export const OTHER_PERSONAL_LIABILITIES: IForm[] = [
  {
    id: "liabilityType",
    type: INPUT_TYPE.SELECT,
    label: "Liability Type",
    key: "liabilityType",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["Credit Cards", "Line Of Credit"],
  },
  {
    id: "lender",
    type: INPUT_TYPE.TEXT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "currentBalance",
    type: INPUT_TYPE.MONEY,
    label: "Current Balance",
    key: "currentBalance",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "loanStatement",
    type: INPUT_TYPE.FILE,
    label: "Loan Statement",
    key: "loanStatement",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastMonthStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastMonthStatement",
      size: 5242880,
    }),
  },
];

const revenueYear = new Date().getFullYear() + 3;

export const REVENUE_FORM: IForm[] = Array(6)
  .fill(0)
  .map((item, index): IForm[] => {
    return [
      {
        id: "revenue_" + (revenueYear - index),
        type: INPUT_TYPE.FILE,
        label: "Revenue " + (revenueYear - index),
        key: "revenue_" + (revenueYear - index),
        value: [],
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 3,
          lg: 3,
          xl: 3,
        },
        documentPath: "net_worth",
        documentCategory: "tax_return",
        schema: PDF_FILE_SCHEMA({
          type: [FILE_TYPE.PDF],
          name: "revenue_" + (revenueYear - index),
          size: 5242880,
        }),
      },
      {
        id: "ebitda_" + (revenueYear - index),
        type: INPUT_TYPE.TEXT,
        label: "EBITDA " + (revenueYear - index),
        key: "ebitda_" + (revenueYear - index),
        value: "",
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 3,
          lg: 3,
          xl: 3,
        },
      },
    ];
  })
  .flat();

export const BUSINESS_TO_BE_FINANCED: IForm[] = [
  {
    id: "addressLine1",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 1",
    key: "addressLine1",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "addressLine2",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 2",
    key: "addressLine2",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "Current Balance",
    key: "currentBalance",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "postalCode",
    type: INPUT_TYPE.TEXT,
    label: "Postal Code",
    key: "postalCode",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.SELECT,
    label: "Province",
    key: "province",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Ontario"],
  },
  {
    id: "country",
    type: INPUT_TYPE.SELECT,
    label: "Country",
    key: "country",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 12,
      lg: 12,
      xl: 12,
    },
    selection: ["Canada"],
  },
  {
    id: "dateFundsRequired",
    type: INPUT_TYPE.DATE,
    label: "Date Funds Required",
    key: "dateFundsRequired",
    value: "",
    hint: "dd/mm/yyyy",
    icon: "badge",
    column: {
      xs: 6,
      sm: 6,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  ...REVENUE_FORM,
];

const businessYear = new Date().getFullYear();

export const FINANCIAL_FORM: IForm[] = Array(6)
  .fill(0)
  .map((item, index): IForm[] => {
    return [
      {
        id: "financialStatement_" + (businessYear - index),
        type: INPUT_TYPE.FILE,
        label: "Financial Statement " + (businessYear - index),
        key: "financialStatement_" + (businessYear - index),
        value: [],
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 3,
          lg: 3,
          xl: 3,
        },
        documentPath: "net_worth",
        documentCategory: "tax_return",
        schema: PDF_FILE_SCHEMA({
          type: [FILE_TYPE.PDF],
          name: "revenue_" + (revenueYear - index),
          size: 5242880,
        }),
      },
      {
        id: "businessNOA_" + (businessYear - index),
        type: INPUT_TYPE.TEXT,
        label: "Business NOA" + (businessYear - index),
        key: "businessNOA_" + (businessYear - index),
        value: "",
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 3,
          lg: 3,
          xl: 3,
        },
      },
      {
        id: "businessTaxReturn_" + (businessYear - index),
        type: INPUT_TYPE.TEXT,
        label: "Business Tax Return " + (businessYear - index),
        key: "businessTaxReturn_" + (businessYear - index),
        value: "",
        hint: "description",
        icon: "mail",
        column: {
          xs: 12,
          sm: 12,
          md: 3,
          lg: 3,
          xl: 3,
        },
      },
    ];
  })
  .flat();

export const BUSINESS_DOCUMENT_FORM: IForm[] = [
  {
    id: "contractInvoice",
    type: INPUT_TYPE.FILE,
    label: "Contract Invoice",
    key: "contractInvoice",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "corporateLogo",
    type: INPUT_TYPE.FILE,
    label: "Corporate Logo",
    key: "corporateLogo",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "businessPlan",
    type: INPUT_TYPE.FILE,
    label: "Business Plan",
    key: "businessPlan",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "articlesOfIncorporation",
    type: INPUT_TYPE.FILE,
    label: "Articles Of Incorporation",
    key: "articlesOfIncorporation",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "leaseAgreement",
    type: INPUT_TYPE.FILE,
    label: "Lease Agreement",
    key: "leaseAgreement",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "insurancePolicy",
    type: INPUT_TYPE.FILE,
    label: "Insurance Policy",
    key: "insurancePolicy",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "insurancePolicy",
    type: INPUT_TYPE.FILE,
    label: "Insurance Policy",
    key: "insurancePolicy",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "120daysAgedAR",
    type: INPUT_TYPE.FILE,
    label: "120 Days Aged A/R",
    key: "120daysAgedAR",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "120daysAgedAP",
    type: INPUT_TYPE.FILE,
    label: "120 Days Aged A/P",
    key: "120daysAgedAP",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "YDFS",
    type: INPUT_TYPE.FILE,
    label: "YDFS",
    key: "YDFS",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  {
    id: "lastYearHSTNOA",
    type: INPUT_TYPE.FILE,
    label: "Last Year's HST NOA",
    key: "lastYearHSTNOA",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
  ...FINANCIAL_FORM,
];

export const BUSINESS_INTEREST_FORM: IForm[] = [
  {
    id: "businessName",
    type: INPUT_TYPE.TEXT,
    label: "Business Name",
    key: "businessName",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "ownership",
    type: INPUT_TYPE.TEXT,
    label: "Ownership",
    key: "ownership",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "industry",
    type: INPUT_TYPE.TEXT,
    label: "Industry",
    key: "industry",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "dateAcquired",
    type: INPUT_TYPE.DATE,
    label: "Date Acquired",
    key: "dateAcquired",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "addressLine1",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 1",
    key: "addressLine1",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "addressLine2",
    type: INPUT_TYPE.TEXT,
    label: "Address Line 2",
    key: "addressLine2",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "city",
    type: INPUT_TYPE.TEXT,
    label: "Current Balance",
    key: "currentBalance",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "postalCode",
    type: INPUT_TYPE.TEXT,
    label: "Postal Code",
    key: "postalCode",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "province",
    type: INPUT_TYPE.SELECT,
    label: "Province",
    key: "province",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["Ontario"],
  },
  {
    id: "country",
    type: INPUT_TYPE.SELECT,
    label: "Country",
    key: "country",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["Canada"],
  },
  {
    id: "businessMarketValue",
    type: INPUT_TYPE.MONEY,
    label: "Business Market Value",
    key: "businessMarketValue",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyIncome",
    type: INPUT_TYPE.MONEY,
    label: "Monthly Income",
    key: "monthlyIncome",
    value: 0,
    hint: "Monthly Income",
    icon: "apartment",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "lender",
    type: INPUT_TYPE.SELECT,
    label: "Lender",
    key: "lender",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: ["BMO", "CIBC", "RBC", "SCOTIA", "TD", "OTHER"],
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "monthlyPayment",
    type: INPUT_TYPE.MONEY,
    label: "Month Payment",
    key: "monthlyPayment",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lastStatement",
    type: INPUT_TYPE.FILE,
    label: "Last Statement",
    key: "lastStatement",
    value: [],
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    documentPath: "net_worth",
    documentCategory: "lastStatement",
    schema: PDF_FILE_SCHEMA({
      type: [FILE_TYPE.PDF],
      name: "lastStatement",
      size: 5242880,
    }),
  },
];

export const ESTATE_PLANNING_GOALS: IForm[] = [
  {
    id: "contactType",
    type: INPUT_TYPE.TEXT,
    label: "Contact Type",
    key: "contactType",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 10,
      sm: 10,
      md: 10,
      lg: 10,
      xl: 10,
    },
  },
  {
    id: "name",
    type: INPUT_TYPE.TEXT,
    label: "Your Name",
    key: "name",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 10,
      sm: 10,
      md: 10,
      lg: 10,
      xl: 10,
    },
  },
  {
    id: "email",
    type: INPUT_TYPE.TEXT,
    label: "Your Email",
    key: "email",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 10,
      sm: 10,
      md: 10,
      lg: 10,
      xl: 10,
    },
  },
  {
    id: "phone",
    type: INPUT_TYPE.PHONE,
    label: "Your phone",
    key: "phone",
    value: "",
    icon: "call",
    hint: "Phone Number",
    column: {
      xs: 10,
      sm: 10,
      md: 10,
      lg: 10,
      xl: 10,
    },
  },
];

export const PERSONAL_STATEMENT_OF_EQUITY: IForm[] = [
  {
    id: "cashAccountReceivable",
    type: INPUT_TYPE.MONEY,
    label: "Cash (Sch A)",
    key: "marketableSecurities",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "taxShelteredInvestment",
    type: INPUT_TYPE.MONEY,
    label: "Overdrafts (Sch J)",
    key: "taxShelteredInvestment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "insurance",
    type: INPUT_TYPE.MONEY,
    label: "Accounts Receivable (Sch A)",
    key: "insurance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "realEstate",
    label: "Credit Cards (Sch J)",
    type: INPUT_TYPE.MONEY,
    key: "realEstate",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "businessInterests",
    type: INPUT_TYPE.MONEY,
    label: "Other Liquid Assets (Sch A)",
    key: "businessInterests",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "vehicles",
    type: INPUT_TYPE.MONEY,
    label: "Marketable Securities (Sch B)",
    key: "vehicles",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Marketable Securities (Sch B)",
    key: "loanBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "lineOfCredit",
    type: INPUT_TYPE.MONEY,
    label: "Tax Sheltered Invest (Sch C)",
    key: "lineOfCredit",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "marketableSecurities",
    type: INPUT_TYPE.MONEY,
    label: "Tax Sheltered Invest (Sch C)",
    key: "marketableSecurities",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "taxShelteredInvestment",
    type: INPUT_TYPE.MONEY,
    label: "Insurance (Sch D)",
    key: "taxShelteredInvestment",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "insurance",
    type: INPUT_TYPE.MONEY,
    label: "Insurance CSV (Sch D)",
    key: "insurance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "realEstate",
    label: "Home (Sch E)",
    type: INPUT_TYPE.MONEY,
    key: "realEstate",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "businessInterests",
    type: INPUT_TYPE.MONEY,
    label: "Home (Sch E)",
    key: "businessInterests",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "vehicles",
    type: INPUT_TYPE.MONEY,
    label: "Mortgages (Sch E)",
    key: "vehicles",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Real Estate (Sch E)",
    key: "loanBalance",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
  {
    id: "lineOfCredit",
    type: INPUT_TYPE.MONEY,
    label: "Business Interests (Sch F)",
    key: "lineOfCredit",
    value: 0,
    hint: "description",
    icon: "monetization_on",
    disabled: true,
    column: {
      xs: 6,
      sm: 6,
      md: 6,
      lg: 6,
      xl: 6,
    },
  },
];

export const PERSONAL_MONTHLY_EXPENSE: IForm[] = [
  {
    id: "marketableSecurities",
    type: INPUT_TYPE.MONEY,
    label: "Marketable Securities",
    key: "marketableSecurities",
    value: 0,
    hint: "Marketable Securities Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "taxShelteredInvestment",
    type: INPUT_TYPE.MONEY,
    label: "Tax Sheltered Investment",
    key: "taxShelteredInvestment",
    value: 0,
    hint: "Tax Sheltered Investment Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "insurance",
    type: INPUT_TYPE.MONEY,
    label: "Insurance",
    key: "insurance",
    value: 0,
    hint: "Insurance Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "realEstate",
    label: "Real Estate",
    type: INPUT_TYPE.MONEY,
    key: "realEstate",
    value: 0,
    hint: "Real Estate Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "businessInterests",
    type: INPUT_TYPE.MONEY,
    label: "Business Interests",
    key: "businessInterests",
    value: 0,
    hint: "Business Interests Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "vehicles",
    type: INPUT_TYPE.MONEY,
    label: "Vehicles",
    key: "vehicles",
    value: 0,
    hint: "Vehicles Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "loanBalance",
    type: INPUT_TYPE.MONEY,
    label: "Loan Balance",
    key: "loanBalance",
    value: 0,
    hint: "Loan Balance Expense",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "lineOfCredit",
    type: INPUT_TYPE.MONEY,
    label: "Line Of Credit",
    key: "lineOfCredit",
    value: 0,
    hint: "Line Of Credit",
    icon: "",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
];

export const PERSONAL_MONTHLY_INCOME: IForm[] = [
  {
    id: "realEstate",
    label: "Real Estate",
    type: INPUT_TYPE.TEXT,
    key: "realEstate",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "marketableSecurities",
    type: INPUT_TYPE.TEXT,
    label: "Marketable Securities",
    key: "marketableSecurities",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "businessInvestments",
    type: INPUT_TYPE.TEXT,
    label: "Business Investments",
    key: "businessInvestments",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "dependantsIncome",
    type: INPUT_TYPE.MONEY,
    label: "Dependants Income",
    key: "dependantsIncome",
    value: 0,
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "income_type",
    type: INPUT_TYPE.SELECT,
    label: "Income type",
    key: "income_type",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: [EMPLOYMENT_TYPE.PERMANENT_FULL_TIME],
  },
  {
    id: "monthlyAmount",
    type: INPUT_TYPE.TEXT,
    label: "Monthly Amount",
    key: "monthlyAmount",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
];

export enum NETWORTH_VALUE {
  CURRENT_BALANCE = "CURRENT_BALANCE",
  MARKET_VALUE = "MARKET_VALUE",
  EQUITY = "EQUITY",
  FACE_VALUE = "FACE_VALUE",
  CSV = "CSV",
}

export type INetWorth = Record<
  SETTING_CATEGORY,
  PartialRecord<Partial<NETWORTH_VALUE>, number> | null
>;

export enum SETTING_CATEGORY_TYPE {
  INITIAL = "INITIAL",
  BASIC_INFORMATION = "BASIC_INFORMATION",
  CURRENT_BALANCE = "CURRENT_BALANCE",
  MARKET_VALUE = "MARKET_VALUE",
  FACE_VALUE = "FACE_VALUE",
  NETWORTH_LIST = "NETWORTH_LIST",
}

export interface ISettingCategory {
  title: string;
  description: string;
  category: SETTING_CATEGORY;
  list: IForm[];
  schema: JoiSchemaBuilder;
  type: SETTING_CATEGORY_TYPE; // type is used to define different style section
}

export const SETTING_COLLECTIONS: Record<
  SETTING_COLLECTION,
  ISettingCategory[]
> = {
  [SETTING_COLLECTION.SECURITY]: [
    {
      title: "Account",
      description: "User Basic Information",
      category: SETTING_CATEGORY.ACCOUNT,
      list: ACCOUNT_INFO,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(
        ACCOUNT_INFO.filter((data) =>
          ["displayName", "phoneNumber"].includes(data.id)
        )
      ),
    },
    {
      title: "Authentication",
      description: "Change Password",
      category: SETTING_CATEGORY.AUTHENTICATION,
      list: ACCOUNT_INFO,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Recognition",
      description: "Change facial and voice recognition",
      category: SETTING_CATEGORY.RECOGNITION,
      list: ACCOUNT_INFO,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
  ],
  [SETTING_COLLECTION.PERSONAL_PROFILE]: [
    {
      title: "Personal Information",
      description: "Personal Information",
      category: SETTING_CATEGORY.PERSONAL_INFORMATION,
      list: PERSONAL_INFORMATION_FORM,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(PERSONAL_INFORMATION_FORM),
    },
    {
      title: "Dependants",
      description: "Your Dependants",
      category: SETTING_CATEGORY.DEPENDANT_INFO,
      list: DEPENDANT_INFO,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(DEPENDANT_INFO),
    },
    {
      title: "Spouse's Information",
      description: "Spouse's Information",
      category: SETTING_CATEGORY.SPOUSE_INFORMATION,
      list: SPOUSE_INFO,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(SPOUSE_INFO),
    },
    {
      title: "Personal Information Uploads",
      description: "Personal Information Uploads",
      category: SETTING_CATEGORY.PERSONAL_INFORMATION_UPLOADS,
      list: PERSONAL_INFORMATION_UPLOADS_FORM,
      type: SETTING_CATEGORY_TYPE.BASIC_INFORMATION,
      schema: SETTINGS_SCHEMA_GENERATOR(PERSONAL_INFORMATION_UPLOADS_FORM),
    },
  ],
  [SETTING_COLLECTION.PERSONAL_RESUME]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      type: SETTING_CATEGORY_TYPE.INITIAL,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      type: SETTING_CATEGORY_TYPE.INITIAL,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.BUSINESS_PROFILE]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      type: SETTING_CATEGORY_TYPE.INITIAL,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      type: SETTING_CATEGORY_TYPE.INITIAL,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.PROFESSIONAL_PROFILE]: [
    {
      title: "Home Address",
      description: "Home Address",
      category: SETTING_CATEGORY.HOME_ADDRESS,
      list: ACCOUNT_INFO,
      type: SETTING_CATEGORY_TYPE.INITIAL,
      schema: SETTINGS_SCHEMA_GENERATOR(ACCOUNT_INFO),
    },
    {
      title: "Biography",
      description: "Your Biography Description",
      category: SETTING_CATEGORY.BIOGRAPHY,
      list: BIOGRAPHY_FORM,
      type: SETTING_CATEGORY_TYPE.INITIAL,
      schema: SETTINGS_SCHEMA_GENERATOR(BIOGRAPHY_FORM),
    },
  ],
  [SETTING_COLLECTION.PERSONAL_NET_WORTH]: [
    {
      title: "Cash And Accounts Receivable",
      description: "asset type, financial institution, statement.",
      category: SETTING_CATEGORY.CASH_ACCOUNTS_RECEIVABLE,
      list: CASH_ACCOUNTS_RECEIVABLE_FORM,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(CASH_ACCOUNTS_RECEIVABLE_FORM),
    },
    {
      title: "Markable Securities",
      description: "Change facial and voice recognition",
      category: SETTING_CATEGORY.MARKABLE_SECURITY,
      list: MARKABLE_SECURITY_FORM,
      type: SETTING_CATEGORY_TYPE.MARKET_VALUE,
      schema: SETTINGS_SCHEMA_GENERATOR(MARKABLE_SECURITY_FORM),
    },
    {
      title: "Tax Sheltered Investment",
      description: "Tax sheltered investment",
      category: SETTING_CATEGORY.TAX_SHELTERED_INVESTMENT,
      list: TAX_SHELTERED_INVESTMENT_FORM,
      type: SETTING_CATEGORY_TYPE.MARKET_VALUE,
      schema: SETTINGS_SCHEMA_GENERATOR(TAX_SHELTERED_INVESTMENT_FORM),
    },
    {
      title: "Insurance",
      description: "Insurance",
      category: SETTING_CATEGORY.INSURANCE,
      list: INSURANCE_FORM,
      type: SETTING_CATEGORY_TYPE.FACE_VALUE,
      schema: SETTINGS_SCHEMA_GENERATOR(INSURANCE_FORM),
    },
    {
      title: "Real Estate",
      description: "Real Estate Property",
      category: SETTING_CATEGORY.REAL_ESTATE,
      list: REAL_ESTATE_FORM,
      type: SETTING_CATEGORY_TYPE.MARKET_VALUE,
      schema: SETTINGS_SCHEMA_GENERATOR(REAL_ESTATE_FORM),
    },
    {
      title: "Vehicles",
      description: "Personal Vehicles",
      category: SETTING_CATEGORY.VEHICLES,
      list: REAL_ESTATE_FORM,
      type: SETTING_CATEGORY_TYPE.MARKET_VALUE,
      schema: SETTINGS_SCHEMA_GENERATOR(REAL_ESTATE_FORM),
    },
    {
      title: "Other Assets",
      description: "Other Assets",
      category: SETTING_CATEGORY.OTHER_ASSETS,
      list: OTHER_ASSEST_FORM,
      type: SETTING_CATEGORY_TYPE.MARKET_VALUE,
      schema: SETTINGS_SCHEMA_GENERATOR(OTHER_ASSEST_FORM),
    },
    {
      title: "Other Loans",
      description: "Other Loans",
      category: SETTING_CATEGORY.OTHER_LOANS,
      list: OTHER_LOANS_FORM,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(OTHER_LOANS_FORM),
    },
    {
      title: "Line Of Credit",
      description: "Line Of Credit",
      category: SETTING_CATEGORY.LINE_OF_CREDIT,
      list: OTHER_LOANS_FORM,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(OTHER_LOANS_FORM),
    },
    {
      title: "Other Personal Liabilities",
      description: "Other Personal Liabilities",
      category: SETTING_CATEGORY.OTHER_PERSONAL_LIABILITIES,
      list: OTHER_PERSONAL_LIABILITIES,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(OTHER_LOANS_FORM),
    },
    {
      title: "Business To Be Financed",
      description: "Business To Be Financed",
      category: SETTING_CATEGORY.BUSINESS_TO_BE_FINANCED,
      list: BUSINESS_TO_BE_FINANCED,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(BUSINESS_TO_BE_FINANCED),
    },
    {
      title: "Business Interest",
      description: "Business Interest",
      category: SETTING_CATEGORY.BUSINESS_INTEREST,
      list: BUSINESS_INTEREST_FORM,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(BUSINESS_INTEREST_FORM),
    },
    {
      title: "Business Documents",
      description: "Business Documents",
      category: SETTING_CATEGORY.BUSINESS_DOCUMENT,
      list: BUSINESS_DOCUMENT_FORM,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(BUSINESS_DOCUMENT_FORM),
    },
    {
      title: "Personal Monthly Income",
      description: "Personal Monthly Income",
      category: SETTING_CATEGORY.BUSINESS_DOCUMENT,
      list: PERSONAL_MONTHLY_INCOME,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(PERSONAL_MONTHLY_INCOME),
    },
    {
      title: "Personal Monthly Expenses",
      description: "Personal Monthly Expenses",
      category: SETTING_CATEGORY.BUSINESS_DOCUMENT,
      list: PERSONAL_MONTHLY_EXPENSE,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(PERSONAL_MONTHLY_EXPENSE),
    },
    {
      title: "Estate Planning & Goals",
      description: "Estate Planning & Goals",
      category: SETTING_CATEGORY.BUSINESS_DOCUMENT,
      list: PERSONAL_MONTHLY_EXPENSE,
      type: SETTING_CATEGORY_TYPE.CURRENT_BALANCE,
      schema: SETTINGS_SCHEMA_GENERATOR(PERSONAL_MONTHLY_EXPENSE),
    },
    {
      title: "Personal Statement Of Equity",
      description: "Personal Statement Of Equity",
      category: SETTING_CATEGORY.PERSONAL_STATEMENT_OF_EQUITY,
      list: [],
      type: SETTING_CATEGORY_TYPE.NETWORTH_LIST,
      schema: SETTINGS_SCHEMA_GENERATOR([]),
    },
    {
      title: "Personal Statement Of Net Income",
      description: "Personal Statement Of Net Income",
      category: SETTING_CATEGORY.PERSONAL_STATEMENT_OF_NET_INCOME,
      list: [],
      type: SETTING_CATEGORY_TYPE.NETWORTH_LIST,
      schema: SETTINGS_SCHEMA_GENERATOR([]),
    },
  ],
};

export const EMPLOYMENT: IForm[] = [
  {
    id: "title",
    type: INPUT_TYPE.TEXT,
    label: "Most Recent Job Title",
    key: "title",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "institution",
    type: INPUT_TYPE.TEXT,
    label: "Most Recent Company",
    key: "institution",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "degree",
    type: INPUT_TYPE.TEXT,
    label: "Degree",
    key: "degree",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "year",
    type: INPUT_TYPE.TEXT,
    label: "Year",
    key: "year",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
  },
  {
    id: "employment_type",
    type: INPUT_TYPE.SELECT,
    label: "Employment type",
    key: "employment_type",
    value: "",
    hint: "description",
    icon: "mail",
    column: {
      xs: 12,
      sm: 12,
      md: 3,
      lg: 3,
      xl: 3,
    },
    selection: [EMPLOYMENT_TYPE.PERMANENT_FULL_TIME],
  },
];
