name: Node.js CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  frontend:
    name: Frontend - ${{ matrix.script }}
    uses: ./.github/workflows/env-build.yml
    strategy:
      fail-fast: false
      matrix:
        script:
          - format
          - test
    with:
      frontend-mono: run ${{ matrix.script }}

  backend-quality:
    name: Backend - ${{ matrix.script }}
    uses: ./.github/workflows/env-build.yml
    strategy:
      fail-fast: false
      matrix:
        script: 
          - format
    with:
      backend-mono: run ${{ matrix.script }}
